# Generated by Django 3.2.9 on 2021-11-03 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_realizado', models.CharField(choices=[('CC', 'Ciência da Computação'), ('AS', 'Análise de Sistemas'), ('EG', 'Engenharias'), ('OU', 'Outros')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.TextField()),
                ('topicos', models.TextField()),
                ('carga_horaria', models.IntegerField()),
                ('image', models.ImageField(upload_to='courso/imagens', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('inscricao_inicio', models.DateField()),
                ('inscricao_fim', models.DateField()),
                ('arquivado', models.BooleanField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
            ],
        ),
    ]
